# Generated by Django 2.2.12 on 2021-10-15 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymoneyapp', '0002_auto_20211015_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttype',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
