# Generated by Django 2.2.12 on 2021-10-15 21:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mymoneyapp', '0003_auto_20211015_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='update_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
