# Generated by Django 3.1.4 on 2021-11-04 07:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mymoneyapp', '0008_user_loginattempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bannedUntil',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
