# Generated by Django 3.1.4 on 2021-11-04 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymoneyapp', '0009_user_banneduntil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bannedUntil',
            field=models.DateTimeField(blank=True),
        ),
    ]
