# Generated by Django 3.1.4 on 2021-11-04 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymoneyapp', '0011_auto_20211104_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bannedUntil',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
