# Generated by Django 3.1.4 on 2021-11-04 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mymoneyapp', '0012_auto_20211104_0145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='bannedUntil',
            new_name='banned_until',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='loginAttempts',
            new_name='login_attempts',
        ),
    ]
