# Generated by Django 3.1.4 on 2021-11-06 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymoneyapp', '0013_auto_20211104_0207'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_attempt',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
